// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.Comments = (function(_super) {
    __extends(Comments, _super);

    function Comments() {
      return Comments.__super__.constructor.apply(this, arguments);
    }

    Comments.prototype.container = "section#comments";

    Comments.prototype.template = "<header>\n	<p class=\"title centered\">{{#establecimiento}} {{name}} {{/establecimiento}}</p>\n   		</header>\n	    <article id=\"art-comments\" class=\"list scroll indented active\">\n	<ul>\n		{{#result}}\n			<li class=\"theme\" id=\"{{id}}\">\n	            <strong>{{comment}}</strong>\n				<small>- {{user}}</small>\n	        </li>\n		{{/result}}\n	</ul>\n	<br>\n	<div class=\"form\">\n		<fieldset>\n	                <textarea placeholder=\"Write something...\" id=\"txtComment\"></textarea>\n	            </fieldset>\n	            <a href=\"#\" data-action=\"saveComment\" class=\"button small accept margin-top on-right\">\n	            	<span class=\"icon ok\"></span><abbr>Enviar</abbr>\n	            </a>\n	</div>\n	    </article>\n	    <footer>\n	        <nav>\n	            <a href=\"#\" data-action=\"back\" id=\"{{#establecimiento}}{{id}}{{/establecimiento}}\">\n			<span class=\"icon chevron-left\"></span>\n	            </a>\n	        </nav>\n	    </footer>";

    return Comments;

  })(Monocle.View);

}).call(this);
