// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.Establishment = (function(_super) {
    __extends(Establishment, _super);

    function Establishment() {
      return Establishment.__super__.constructor.apply(this, arguments);
    }

    Establishment.prototype.container = "section#establishment article#art-establishment";

    Establishment.prototype.template = "{{#result}}\n	<div class=\"empty\" id=\"{{id}}\">\n		<span class=\"icon map-marker\"></span>\n		<strong>{{name}}</strong>\n	            <small>{{description}}</small>\n	            <small>{{address}}</small>\n	            <small>{{telephone}}</small>\n        	</div>\n{{/result}}";

    return Establishment;

  })(Monocle.View);

}).call(this);
