// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.Favorites = (function(_super) {
    __extends(Favorites, _super);

    function Favorites() {
      return Favorites.__super__.constructor.apply(this, arguments);
    }

    Favorites.prototype.container = "section#favorites article#art-favorites ul";

    Favorites.prototype.template = "{{#result}}\n	<li class=\"theme\" id=\"{{id}}\">\n		<span class=\"tag count on-right\">{{telephone}}</span>\n	            <strong>{{name}}</strong>\n		<small>{{address}}</small>\n	</li>\n{{/result}}";

    return Favorites;

  })(Monocle.View);

}).call(this);
