// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__View.Main = (function(_super) {
  __extends(Main, _super);

  function Main() {
    _ref = Main.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Main.prototype.container = "section#main";

  Main.prototype.template = "<header>\n	<h1 class=\"title centered\">Si Joven</h1>\n</header>\n<article id=\"art_main_map\" class=\"list indented scroll active\">\n	    	<div class=\"form\">\n		<fieldset>\n			<span id=\"btnSearch\" class=\"icon search\"></span>\n	                <input type=\"text\" id=\"txtSearch\" placeholder=\"Buscar...\">\n	            </fieldset>\n	</div>\n	<nav style=\"text-align: center;\">\n    			<a id=\"edad\" class=\"button large margin-left\"><span>Edad</span></a>\n    			<a id=\"ubicacion\" class=\"button large margin-left\"><span class=\"icon map-marker\"></span></a>\n    			<a id=\"entidad\" class=\"button large margin-left\"><span class=\"icon briefcase\"></span></a>\n    			<a id=\"categoria\" class=\"button large margin-left\"><span class=\"icon list-ol\"></span></a>\n	</nav>\n	<ul>\n		{{#result}}\n			<li class=\"selectable\" id=\"{{PkOferta}}\">\n				<span class=\"tag count on-right\">{{EdadObejtivo}}</span>\n	            <strong>{{EntidadNombre}}</strong>\n				<small>{{Oportunidad}}</small>\n				<small>{{FechaVencimiento}}</small>\n	        </li>\n		{{/result}}\n	</ul>\n</article>\n<footer>\n	<nav>\n		<a href=\"#\" class=\"active\" data-action=\"search\" data-icon=\"search\">\n			<span class=\"icon search\"></span></a>\n		<a href=\"#\" id=\"star\" data-action=\"star\" data-icon=\"star\"><span class=\"icon star\"></span></a></a>\n		<a href=\"#\" data-view-section=\"favorites\" id=\"footerFavorite\" data-icon=\"heart\"><span class=\"icon heart\"></span></a></a>\n		<a href=\"#\" data-view-section=\"profile\" data-action=\"hv\"><span class=\"icon user\"></span></a>\n	</nav>\n</footer>";

  return Main;

})(Monocle.View);
