// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.Ofert = (function(_super) {
    __extends(Ofert, _super);

    function Ofert() {
      return Ofert.__super__.constructor.apply(this, arguments);
    }

    Ofert.prototype.container = "section#ofert";

    Ofert.prototype.template = "<header>\n	<nav class=\"left\">\n		<a href=\"#\" id=\"back\"><span class=\"icon chevron-left\"></span></a>\n	</nav>\n	<p class=\"title centered\">{{#result}} {{EntidadNombre}} {{/result}}</p>\n   		</header>\n	    <article id=\"art-ofert\" class=\"list scroll indented active\">\n	    	{{#result}}\n    	<div class=\"empty\" id=\"{{PkOferta}}\">\n    		<nav class=\"on-right\" id=\"addFavorite\">\n				<span class=\"icon heart\"></span>\n			</nav>\n			<span class=\"tag count on-left\">{{EdadObejtivo}}</span>\n			<span class=\"icon paper-clip\"></span>\n            <small>{{Oportunidad}}</small>\n            <small>Ubicacion: {{Ubicacion}}</small>\n            <small>{{UrlFuente}}</small>\n	        	</div>\n	        {{/result}}\n	    </article>";

    return Ofert;

  })(Monocle.View);

}).call(this);
