// Generated by CoffeeScript 1.7.1
(function() {
  var EstablishmentCtrl,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EstablishmentCtrl = (function(_super) {
    var establishment, parseResponse, parseResponseComments;

    __extends(EstablishmentCtrl, _super);

    function EstablishmentCtrl() {
      return EstablishmentCtrl.__super__.constructor.apply(this, arguments);
    }

    EstablishmentCtrl.prototype.events = {
      "tap button[data-action=logout]": "logout",
      "tap a[data-action=favorites]": "loadFavorites",
      "tap a[data-action=comments]": "loadComments"
    };

    establishment = null;

    EstablishmentCtrl.prototype.initialize = function(id) {
      var data, url;
      url = "http://app-back.eu1.frbit.net/api/establishment";
      data = {
        establishment_id: id
      };
      return Lungo.Service.post(url, data, parseResponse, "json");
    };

    parseResponse = function(data) {
      var view;
      console.log(data);
      if (data.status === 200) {
        establishment = {
          establecimiento: [
            {
              id: data.result[0].id,
              name: data.result[0].name
            }
          ]
        };
        $$('article#art-establishment').html('');
        view = new __View.Establishment({
          model: data
        });
        view.append(data);
        Lungo.Router.section('establishment');
      } else {
        console.log(data);
      }
      return Lungo.Notification.hide();
    };

    EstablishmentCtrl.prototype.loadFavorites = function() {
      Lungo.Notification.show();
      return __Controller.Favorites.initialize();
    };

    EstablishmentCtrl.prototype.logout = function() {
      return __Controller.Main.onLogout();
    };

    EstablishmentCtrl.prototype.loadComments = function(e) {
      var data, id, url;
      id = e.currentTarget.parentElement.parentElement.parentElement.childNodes[3].childNodes[0].id;
      url = "http://app-back.eu1.frbit.net/api/establishment/comments";
      data = {
        establishment_id: id
      };
      return Lungo.Service.post(url, data, parseResponseComments, "json");
    };

    parseResponseComments = function(data) {
      return __Controller.Comments.initialize(establishment, data);
    };

    return EstablishmentCtrl;

  })(Monocle.Controller);

  __Controller.Establishment = new EstablishmentCtrl("section#establishment");

}).call(this);
