// Generated by CoffeeScript 1.6.3
var FavoritesCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FavoritesCtrl = (function(_super) {
  __extends(FavoritesCtrl, _super);

  function FavoritesCtrl() {
    _ref = FavoritesCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  FavoritesCtrl.prototype.events = {
    "tap a#main": "onMain",
    "tap a#star": "onStar"
  };

  FavoritesCtrl.prototype.onMain = function() {
    __Controller.Main.initialize({
      onStar: function() {}
    })();
    return __Controller.Filter.initialize();
  };

  return FavoritesCtrl;

})(Monocle.Controller);

__Controller.Favorites = new FavoritesCtrl("section#favorites");
