// Generated by CoffeeScript 1.6.3
var FavoritesCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FavoritesCtrl = (function(_super) {
  var parseResponse;

  __extends(FavoritesCtrl, _super);

  function FavoritesCtrl() {
    _ref = FavoritesCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  FavoritesCtrl.prototype.events = {
    "tap article#art-favorites ul li": "onTapStablishment"
  };

  FavoritesCtrl.prototype.initialize = function() {
    var data, url;
    url = "http://app-back.eu1.frbit.net/api/user/favorites";
    data = {
      token: 'eccbc87e4b5ce2fe28308fd9f2a7baf3'
    };
    return Lungo.Service.post(url, data, parseResponse, "json");
  };

  parseResponse = function(data) {
    var view;
    if (data.status === 200) {
      $$('article#art-favorites ul').html('');
      view = new __View.Favorites({
        model: data
      });
      view.append(data);
      Lungo.Router.section('favorites');
    } else {
      console.log(data);
    }
    return Lungo.Notification.hide();
  };

  FavoritesCtrl.prototype.onTapStablishment = function(e) {
    var id;
    Lungo.Notification.show();
    id = e.currentTarget.id;
    return __Controller.Establishment.initialize(id);
  };

  return FavoritesCtrl;

})(Monocle.Controller);

__Controller.Favorites = new FavoritesCtrl("section#favorites");
