// Generated by CoffeeScript 1.6.3
var FilterCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FilterCtrl = (function(_super) {
  var parseFilter;

  __extends(FilterCtrl, _super);

  function FilterCtrl() {
    _ref = FilterCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  FilterCtrl.prototype.events = {
    "tap li.selectable": "onOfert",
    "tap a#onSearch": "OnSearch",
    "tap a#footerFavorite": "OnFavorite"
  };

  FilterCtrl.prototype.initialize = function() {
    var url;
    Lungo.Notification.show();
    url = "http://rumbon.gopagoda.com/api/oferts";
    return Lungo.Service.get(url, "", parseFilter, "json");
  };

  parseFilter = function(data) {
    var result, view;
    result = {
      result: data
    };
    $$('section#filters').html('');
    view = new __View.Filter({
      model: result
    });
    view.append(result);
    Lungo.Router.section('filters');
    return Lungo.Notification.hide();
  };

  FilterCtrl.prototype.OnSearch = function() {
    return __Controller.Main.initialize();
  };

  FilterCtrl.prototype.onOfert = function(e) {
    var id, myMap, row, _i, _len, _ref1;
    myMap = {};
    _ref1 = result.result;
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      row = _ref1[_i];
      myMap[row.PkOferta] = {
        result: [
          {
            PkOferta: row.PkOferta,
            EntidadNombre: row.EntidadNombre,
            EdadObejtivo: row.EdadObejtivo,
            Oportunidad: row.Oportunidad,
            Ubicacion: row.Ubicacion,
            UrlFuente: row.UrlFuente
          }
        ]
      };
    }
    id = e.currentTarget.id;
    Lungo.Notification.show();
    return __Controller.Ofert.initialize(myMap[id]);
  };

  FilterCtrl.prototype.OnFavorite = function() {
    return __Controller.Favorites.initialize();
  };

  return FilterCtrl;

})(Monocle.Controller);

__Controller.Filter = new FilterCtrl("section#filters");
