// Generated by CoffeeScript 1.6.3
var LoginCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LoginCtrl = (function(_super) {
  var parseResponse;

  __extends(LoginCtrl, _super);

  function LoginCtrl() {
    _ref = LoginCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  LoginCtrl.prototype.events = {
    "tap button[data-action=login]": "onLogin",
    "tap button[data-action=callsignup]": "callSignup"
  };

  LoginCtrl.prototype.initialize = function() {
    var age, name;
    Lungo.Notification.show();
    name = localStorage.getItem('name');
    age = localStorage.getItem('age');
    if (name && age) {
      return __Controller.Main.initialize();
    } else {
      return Lungo.Notification.hide();
    }
  };

  LoginCtrl.prototype.onLogin = function() {
    var data, url;
    if (this.user.val() && this.password.val()) {
      Lungo.Notification.show();
      url = "http://app-back.eu1.frbit.net/api/user/login";
      data = {
        email: this.user.val(),
        password: this.password.val()
      };
      Lungo.Service.post(url, data, parseResponse, "json");
      this.user.val("");
      return this.password.val("");
    } else {
      return Lungo.Notification.error("Por favor llene todos los campos", "Para acceder necesitas llenar todos los campos correctamente", "warning-sign", 5);
    }
  };

  parseResponse = function(data) {
    if (data.status === 200) {
      localStorage.setItem("token", data.result.token);
      __Controller.Main.initialize();
    } else {
      console.log(data);
      Lungo.Notification.error("Error", "Error al logearte", "warning-sign", 2)();
    }
    return Lungo.Notification.hide();
  };

  LoginCtrl.prototype.callSignup = function() {
    return Lungo.Router.section("signup");
  };

  return LoginCtrl;

})(Monocle.Controller);

Lungo.ready(function() {
  __Controller.Login = new LoginCtrl("section#login");
  return __Controller.Login.initialize();
});
