// Generated by CoffeeScript 1.7.1
(function() {
  var MainCtrl,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MainCtrl = (function(_super) {
    __extends(MainCtrl, _super);

    function MainCtrl() {
      return MainCtrl.__super__.constructor.apply(this, arguments);
    }

    MainCtrl.prototype.events = {
      "tap a[data-action=locate]": "onLocate"
    };

    MainCtrl.prototype.initialize = function() {
      return Lungo.Router.section('main');
    };

    return MainCtrl;

  })(Monocle.Controller);

  Lungo.ready(function() {
    __Controller.Main = new MainCtrl("section#main");
    return __Controller.Main.initialize();
  });

}).call(this);
