// Generated by CoffeeScript 1.6.3
var MainCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MainCtrl = (function(_super) {
  __extends(MainCtrl, _super);

  function MainCtrl() {
    _ref = MainCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  MainCtrl.prototype.events = {
    "tap a[data-action=locate]": "onLocate",
    "tap button[data-action=logout]": "onLogout",
    "tap li#mainHome": "onMain",
    "tap li#userFavorites": "onFavorites",
    "tap li#usercategories": "onCategories"
  };

  MainCtrl.prototype.initialize = function() {
    var age, name;
    name = localStorage.getItem('name');
    age = localStorage.getItem('age');
    if (name && age) {
      return Lungo.Router.section('main');
    } else {
      return console.log('no');
    }
  };

  MainCtrl.prototype.onMain = function() {
    Lungo.Notification.show();
    Lungo.Router.section('main');
    return Lungo.Notification.hide();
  };

  MainCtrl.prototype.onFavorites = function() {
    Lungo.Notification.show();
    return __Controller.Favorites.initialize();
  };

  MainCtrl.prototype.onCategories = function() {
    Lungo.Notification.show();
    Lungo.Router.section('categories');
    return Lungo.Notification.hide();
  };

  return MainCtrl;

})(Monocle.Controller);

Lungo.ready(function() {
  __Controller.Main = new MainCtrl("section#main");
  __Controller.Main = new MainCtrl("aside#features");
  return __Controller.Main.initialize();
});
