// Generated by CoffeeScript 1.7.1
(function() {
  var OfertCtrl,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OfertCtrl = (function(_super) {
    var oferta;

    __extends(OfertCtrl, _super);

    function OfertCtrl() {
      return OfertCtrl.__super__.constructor.apply(this, arguments);
    }

    OfertCtrl.prototype.events = {
      "tap a#back": "onBack",
      "tap a#addFavorite": "onAddFavorite",
      "tap a#facebook": "onFacebook",
      "tap a#sendhv": "OnSend"
    };

    oferta = null;

    OfertCtrl.prototype.initialize = function(data) {
      var view;
      oferta = data;
      $$('section#ofert').html('');
      view = new __View.Ofert({
        model: data
      });
      view.append(data);
      Lungo.Router.section('ofert');
      return Lungo.Notification.hide();
    };

    OfertCtrl.prototype.onBack = function() {
      return __Controller.Main.initialize();
    };

    OfertCtrl.prototype.onAddFavorite = function() {
      var db;
      db = window.openDatabase("SiJoven", "1.0", "Test DB", 1000000);
      return db.transaction(__Controller.Ofert.Query, __Controller.Ofert.Error, __Controller.Ofert.success);
    };

    OfertCtrl.prototype.Query = function(tx) {
      return tx.executeSql('INSERT INTO favorites (PkOferta unique, EntidadNombre, EdadObejtivo, Oportunidad, Ubicacion, UrlFuente ) VALUES ("' + oferta.result[0].PkOferta + '","' + oferta.result[0].EntidadNombre + '","' + oferta.result[0].EdadObejtivo + '","' + oferta.result[0].Oportunidad + '","' + oferta.result[0].Ubicacion + '","' + oferta.result[0].UrlFuente + '")');
    };

    OfertCtrl.prototype.onFacebook = function() {
      return window.plugins.socialsharing.share(oferta.result[0].Oportunidad, 'Te Invito a que le heches un vistazo', null, oferta.result[0].UrlFuente);
    };

    OfertCtrl.prototype.OnSend = function() {
      return window.plugin.email.open({
        to: [oferta.result[0].UrlFuente],
        subject: 'Saludos este es mi perfil',
        body: '<h3>TEST</h3><h2>TEST</h2><h1>TEST</h1>',
        isHtml: true
      });
    };

    return OfertCtrl;

  })(Monocle.Controller);

  __Controller.Ofert = new OfertCtrl("section#ofert");

}).call(this);
