// Generated by CoffeeScript 1.6.3
var ProfileCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ProfileCtrl = (function(_super) {
  __extends(ProfileCtrl, _super);

  function ProfileCtrl() {
    _ref = ProfileCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ProfileCtrl.prototype.elements = {
    "#txtCompletename": "nombre",
    "#datepicker": "fecha",
    "#txtEmail": "correo",
    "#txtcomentario": "comentario",
    "#txtnivel": "nivel"
  };

  ProfileCtrl.prototype.events = {
    "tap input#datepicker": "onDatePicker",
    "tap button": "onSave",
    "tap a#star": "onStar"
  };

  ProfileCtrl.prototype.onDatePicker = function() {
    return datePicker.show({
      date: new Date(),
      mode: 'date'
    }, function(date) {
      var año, dia, mes;
      mes = date.getDate();
      dia = date.getMonth();
      año = date.getFullYear();
      return $$('#datepicker').val(dia + "/" + mes + "/" + año);
    });
  };

  ProfileCtrl.prototype.onStar = function() {
    return __Controller.Filter.initialize();
  };

  ProfileCtrl.prototype.onSave = function() {
    var db;
    db = window.openDatabase("SiJoven", "1.0", "Test DB", 1000000);
    return db.transaction(__Controller.Profile.Query, __Controller.Profile.Error, __Controller.Profile.success);
  };

  ProfileCtrl.prototype.Query = function(tx) {
    tx.executeSql('INSERT INTO profile (id PRIMARY KEY, nombre, fecha, email, comentario, nivel ) VALUES ( 1, ' + $$("#txtCompletename").val() + '","' + $$("#datepicker").val() + '","' + $$("#txtEmail").val() + '","' + $$("#txtcomentario").val() + '","' + $$("#txtnivel").val() + '"")');
    return tx.executeSql('UPDATE profile SET nombre = "' + $$("#txtCompletename").val() + '",' + ' fecha = "' + $$("#datepicker").val() + '",' + ' email = "' + $$("#txtEmail").val() + '",' + ' comentario = "' + $$("#txtcomentario").val() + '",' + ' nivel = "' + $$("#txtnivel").val() + '")');
  };

  return ProfileCtrl;

})(Monocle.Controller);

__Controller.Profile = new ProfileCtrl("section#profile");
