// Generated by CoffeeScript 1.6.3
var ProfileCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ProfileCtrl = (function(_super) {
  __extends(ProfileCtrl, _super);

  function ProfileCtrl() {
    _ref = ProfileCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ProfileCtrl.prototype.events = {
    "tap input#datepicker": "onDatePicker"
  };

  ProfileCtrl.prototype.onDatePicker = function() {
    return datePicker.show({
      date: new Date(),
      mode: 'datetime'
    }, function(date) {
      return $$('#datepicker').val("" + date);
    });
  };

  return ProfileCtrl;

})(Monocle.Controller);

__Controller.Profile = new ProfileCtrl("section#profile");
