// Generated by CoffeeScript 1.6.3
var SignupCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SignupCtrl = (function(_super) {
  __extends(SignupCtrl, _super);

  function SignupCtrl() {
    _ref = SignupCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  SignupCtrl.prototype.elements = {
    "#txtName": "user",
    "#txtEdad": "age"
  };

  SignupCtrl.prototype.events = {
    "tap button[data-action=signup]": "onSignup",
    "tap button[data-action=calllogin]": "callLogin"
  };

  SignupCtrl.prototype.onSignup = function() {
    if (this.user.val() && this.age.val()) {
      Lungo.Notification.show();
      localStorage.setItem("name", this.user.val());
      localStorage.setItem("age", this.age.val());
      this.user.val("");
      this.age.val("");
      __Controller.Main.initialize;
      return Lungo.Notification.hide();
    } else {
      return Lungo.Notification.error("Por favor llene todos los campos", "Para registrarte necesitas llenar todos los campos", "warning-sign", 5);
    }
  };

  SignupCtrl.prototype.callLogin = function() {
    return Lungo.Router.section("login");
  };

  return SignupCtrl;

})(Monocle.Controller);

__Controller.Signup = new SignupCtrl("section#signup");
